//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBestProjectInTheWorld.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsAccindent
    {
        public int id { get; set; }
        public int carsAccindentId { get; set; }
        public int accindentId { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual RoadAccindents RoadAccindents { get; set; }
    }
}
