//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBestProjectInTheWorld.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.CarsAccindent = new HashSet<CarsAccindent>();
        }
    
        public int id { get; set; }
        public string VIN { get; set; }
        public Nullable<double> Year { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<int> EngineId { get; set; }
        public Nullable<int> ManufaturerId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public int driverId { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        public virtual EngineTypes EngineTypes { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Models Models { get; set; }
        public virtual TypeDrives TypeDrives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarsAccindent> CarsAccindent { get; set; }
    }
}
