//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBestProjectInTheWorld.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangedStatusHistory
    {
        public int Id { get; set; }
        public int licencId { get; set; }
        public int changedFromStatusID { get; set; }
        public int changedToStatusId { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Licences Licences { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Statuses Statuses1 { get; set; }
    }
}
