//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBestProjectInTheWorld.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licences
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Licences()
        {
            this.ChangedStatusHistory = new HashSet<ChangedStatusHistory>();
            this.Drivers = new HashSet<Drivers>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> licenceDate { get; set; }
        public Nullable<System.DateTime> expireDate { get; set; }
        public string categories { get; set; }
        public string licenceSeries { get; set; }
        public Nullable<int> licenceNumber { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChangedStatusHistory> ChangedStatusHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drivers> Drivers { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
